apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: z-kubecost
  namespace: istio-system
spec:
  match: match(destination.service.host, "*.kubecost.svc.cluster.local")
  requestHeaderOperations:
  - name: Authorization
    operation: REMOVE
